[package]
name = "bobawallet"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
crossbeam-channel = "0.5.15"
global-hotkey = "0.7.0"
gpui = { git = "https://github.com/zed-industries/zed" }
